server:
  port: 8761

spring:
  application:
    name: muscledia-service-discovery

eureka:
  instance:
    hostname: service-discovery
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000